"""rename lessons

Revision ID: a4079650d9e8
Revises: 4e2b6a90cbb0
Create Date: 2021-11-28 23:36:54.601340

"""
from alembic import op
import sqlalchemy as sa
import flask_authorize

# revision identifiers, used by Alembic.
revision = 'a4079650d9e8'
down_revision = '4e2b6a90cbb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lesson',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('deadline', sa.String(length=255), nullable=True),
    sa.Column('other_permissions', flask_authorize.mixins.PipedList(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('owner_permissions', flask_authorize.mixins.PipedList(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('group_permissions', flask_authorize.mixins.PipedList(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lesson_name'), 'lesson', ['name'], unique=False)
    op.drop_index('ix_articles_name', table_name='articles')
    op.drop_table('articles')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('articles',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=True),
    sa.Column('deadline', sa.VARCHAR(length=255), nullable=True),
    sa.Column('other_permissions', sa.TEXT(), nullable=True),
    sa.Column('owner_id', sa.INTEGER(), nullable=True),
    sa.Column('owner_permissions', sa.TEXT(), nullable=True),
    sa.Column('group_id', sa.INTEGER(), nullable=True),
    sa.Column('group_permissions', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_articles_name', 'articles', ['name'], unique=False)
    op.drop_index(op.f('ix_lesson_name'), table_name='lesson')
    op.drop_table('lesson')
    # ### end Alembic commands ###
